backend:
  name: git-gateway
  branch: main

site_url: https://grand-sunburst-fd821e.netlify.app
display_url: https://grand-sunburst-fd821e.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articoli"
    label: "Articoli"
    folder: "_articoli"
    create: true
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Numero", name: "numero", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "select",
          options: ["Prosa", "Poesia", "Saggio", "Rubrica"] }
      - { label: "Testo", name: "body", widget: "markdown" }

  - name: "galleria"
    label: "Galleria"
    folder: "_galleria"
    create: true
    fields:
      - { label: "Titolo opera", name: "title", widget: "string" }
      - { label: "Numero", name: "numero", widget: "string" }
      - { label: "Tipo", name: "tipo", widget: "select",
          options: ["Illustrazione", "Fotografia", "Opera"] }
      - { label: "Immagine", name: "image", widget: "image" }
